name: flutter_bugfender
description: Flutter plugin to enable Bugfender reporting (iOS, Android and web support).
version: 2.0.0-web.1
homepage: https://bugfender.com
repository: https://github.com/bugfender/BugfenderSDK-Flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.bugfender.flutterbugfender
        pluginClass: FlutterBugfenderPlugin
      ios:
        pluginClass: FlutterBugfenderPlugin
      web:
        pluginClass: WebFlutterBugfender
        fileName: flutter_bugfender_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  js: ^0.6.3-nullsafety.0

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"
